### ISSUE TITLE
OTP server on dev.opentripplanner.org should plan NZ GTFS routes

### ISSUE THREAD

**Issue by bertspaan** [waagsociety/noordzuidlijn#1]
GTFS file: https://github.com/waagsociety/noordzuidlijn/blob/gh-pages/noordzuidlijn/noordzuidlijn.gtfs.zip

How can I include/exclude the Noordzuidlijn in a single OTP API call? Or should we use different routerIds to do this?

**Comment by abyrd** [comment]
The easiest way to do it (and the way we plan to use in most spatial analysis in the future) is to just activate/disactivate a route that is present in a single graph (i.e. don't make a separate router/graph for the alternative scenarios). 

The parameter to ban a route is bannedRoutes=agency_routeName_routeId where routeName can be empty. Yes, this is bizarre but that's how it is for now. So to ban the NZ line you'd use bannedRoutes=NZ__generated_0 (two underscores after agency ID).

This assumes the latest version of the noordzuid repository where I added a unique agency ID.

**Comment by abyrd** [comment]
Now that I have this up and running, I see that the NZ lijn trips tend to alight at stop 4 as if the route doesn't continue past there. I'll need to investigate.

**Comment by abyrd** [comment]
I originally thought OTP was overwriting the geom2gtfs default agency id of 0 but this is not the case. So if we use the GTFS feed from this repo as of 9e19f1db904e1c1 the banned route string should be 0__generated_0. I have confirmed that starting with http://dev.opentripplanner.org:9090/?module=planner&fromPlace=52.40074312027673%2C4.9294281005859375&toPlace=52.34289063530758%2C4.874153137207031&time=10%3A11am&date=04-17-2015&mode=TRANSIT%2CWALK&maxWalkDistance=1207.008&arriveBy=false&wheelchair=false&showIntermediateStops=false&itinIndex=0 

then adding a bannedRoutes parameter to the url: http://dev.opentripplanner.org:9090/?module=planner&fromPlace=52.40074312027673%2C4.9294281005859375&toPlace=52.34289063530758%2C4.874153137207031&time=10%3A11am&date=04-17-2015&mode=TRANSIT%2CWALK&maxWalkDistance=1207.008&arriveBy=false&wheelchair=false&showIntermediateStops=false&itinIndex=0&bannedRoutes=0__generated_0

The NZlijn is no longer used.

**Comment by bertspaan** [comment]
Thanks! Works perfectly!
